// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"hertz-session/biz/dal"
	"hertz-session/pkg/render"
)

func main() {
	dal.Init()
	h := server.Default()
	register(h)
	render.Render(h)
	h.Spin()
}
