// Code generated by hertz generator.

package main

import (
	"hertz-session/biz/handler"
	"hertz-session/biz/handler/user"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.GET("/logout", user.Logout)
}
