// Code generated by hertz generator.

package user

import (
	"context"
	hutils "github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/hertz-contrib/sessions"
	"hertz-session/biz/dal/mysql"
	"hertz-session/pkg/consts"
	"hertz-session/pkg/utils"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"hertz-session/biz/model/user"
)

// Register .
// @router /register [POST]
func Register(_ context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.HTML(http.StatusOK, "register.html", hutils.H{
			"message": utils.RenderMsg(err.Error()),
		})
		return
	}
	users, err := mysql.FindUserByNameOrEmail(req.Username, req.Email)
	if err != nil {
		c.HTML(http.StatusOK, "register.html", hutils.H{
			"message": utils.RenderMsg(err.Error()),
		})
		return
	}
	if len(users) != 0 {
		c.HTML(http.StatusOK, "register.html", hutils.H{
			"message": utils.RenderMsg(consts.RegisterErr),
		})
		return
	}
	if err = mysql.CreateUsers([]*mysql.User{
		{
			Username: req.Username,
			Password: utils.MD5(req.Password),
			Email:    req.Email,
		},
	}); err != nil {
		c.HTML(http.StatusOK, "register.html", hutils.H{
			"message": utils.RenderMsg(consts.RegisterErr),
		})
		return
	}
	c.HTML(http.StatusOK, "register.html", hutils.H{
		"message": consts.Success,
	})
}

// Login .
// @router /login [POST]
func Login(_ context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.HTML(http.StatusOK, "login.html", hutils.H{
			"message": utils.RenderMsg(err.Error()),
		})
		return
	}
	users, err := mysql.CheckUser(req.Username, utils.MD5(req.Password))
	if err != nil {
		c.HTML(http.StatusOK, "login.html", hutils.H{
			"message": utils.RenderMsg(err.Error()),
		})
		return
	}
	if len(users) == 0 {
		c.HTML(http.StatusOK, "login.html", hutils.H{
			"message": utils.RenderMsg(consts.LoginErr),
		})
		return
	}
	session := sessions.Default(c)
	session.Set(consts.Username, req.Username)
	_ = session.Save()
	c.Redirect(http.StatusMovedPermanently, []byte("/page"))
}
